/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthAppearanceIndexRouteImport } from './routes/_auth/appearance/index'
import { Route as AuthAudienceIndexRouteImport } from './routes/_auth/audience/index'
import { Route as AuthCommentsIndexRouteImport } from './routes/_auth/comments/index'
import { Route as AuthContentTypesIndexRouteImport } from './routes/_auth/content-types/index'
import { Route as AuthContentTypesSlugRouteImport } from './routes/_auth/content-types/$slug'
import { Route as AuthEntriesTypeRouteImport } from './routes/_auth/entries/$type'
import { Route as AuthFormsIndexRouteImport } from './routes/_auth/forms/index'
import { Route as AuthHealthIndexRouteImport } from './routes/_auth/health/index'
import { Route as AuthMediaIndexRouteImport } from './routes/_auth/media/index'
import { Route as AuthMenusIndexRouteImport } from './routes/_auth/menus/index'
import { Route as AuthModelsIndexRouteImport } from './routes/_auth/models/index'
import { Route as AuthPagesIndexRouteImport } from './routes/_auth/pages/index'
import { Route as AuthPatternsIndexRouteImport } from './routes/_auth/patterns/index'
import { Route as AuthPluginsIndexRouteImport } from './routes/_auth/plugins/index'
import { Route as AuthPostsIndexRouteImport } from './routes/_auth/posts/index'
import { Route as AuthPostsPostIdRouteImport } from './routes/_auth/posts/$postId'
import { Route as AuthPrivacyIndexRouteImport } from './routes/_auth/privacy/index'
import { Route as AuthProfileIndexRouteImport } from './routes/_auth/profile/index'
import { Route as AuthRolesIndexRouteImport } from './routes/_auth/roles/index'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthTaxonomyIndexRouteImport } from './routes/_auth/taxonomy/index'
import { Route as AuthUsersIndexRouteImport } from './routes/_auth/users/index'
import { Route as AuthWebhooksIndexRouteImport } from './routes/_auth/webhooks/index'
import { Route as AuthAppearanceStudioDraftIdRouteImport } from './routes/_auth/appearance/studio.$draftId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAppearanceIndexRoute = AuthAppearanceIndexRouteImport.update({
  id: '/appearance/',
  path: '/appearance/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAudienceIndexRoute = AuthAudienceIndexRouteImport.update({
  id: '/audience/',
  path: '/audience/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCommentsIndexRoute = AuthCommentsIndexRouteImport.update({
  id: '/comments/',
  path: '/comments/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthContentTypesIndexRoute = AuthContentTypesIndexRouteImport.update({
  id: '/content-types/',
  path: '/content-types/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthContentTypesSlugRoute = AuthContentTypesSlugRouteImport.update({
  id: '/content-types/$slug',
  path: '/content-types/$slug',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEntriesTypeRoute = AuthEntriesTypeRouteImport.update({
  id: '/entries/$type',
  path: '/entries/$type',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFormsIndexRoute = AuthFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHealthIndexRoute = AuthHealthIndexRouteImport.update({
  id: '/health/',
  path: '/health/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMediaIndexRoute = AuthMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMenusIndexRoute = AuthMenusIndexRouteImport.update({
  id: '/menus/',
  path: '/menus/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthModelsIndexRoute = AuthModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPagesIndexRoute = AuthPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPatternsIndexRoute = AuthPatternsIndexRouteImport.update({
  id: '/patterns/',
  path: '/patterns/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPluginsIndexRoute = AuthPluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPostsIndexRoute = AuthPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPostsPostIdRoute = AuthPostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPrivacyIndexRoute = AuthPrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileIndexRoute = AuthProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRolesIndexRoute = AuthRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTaxonomyIndexRoute = AuthTaxonomyIndexRouteImport.update({
  id: '/taxonomy/',
  path: '/taxonomy/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWebhooksIndexRoute = AuthWebhooksIndexRouteImport.update({
  id: '/webhooks/',
  path: '/webhooks/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAppearanceStudioDraftIdRoute =
  AuthAppearanceStudioDraftIdRouteImport.update({
    id: '/appearance/studio/$draftId',
    path: '/appearance/studio/$draftId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/setup': typeof SetupRoute
  '/verify': typeof VerifyRoute
  '/content-types/$slug': typeof AuthContentTypesSlugRoute
  '/entries/$type': typeof AuthEntriesTypeRoute
  '/posts/$postId': typeof AuthPostsPostIdRoute
  '/appearance/': typeof AuthAppearanceIndexRoute
  '/audience/': typeof AuthAudienceIndexRoute
  '/comments/': typeof AuthCommentsIndexRoute
  '/content-types/': typeof AuthContentTypesIndexRoute
  '/forms/': typeof AuthFormsIndexRoute
  '/health/': typeof AuthHealthIndexRoute
  '/media/': typeof AuthMediaIndexRoute
  '/menus/': typeof AuthMenusIndexRoute
  '/models/': typeof AuthModelsIndexRoute
  '/pages/': typeof AuthPagesIndexRoute
  '/patterns/': typeof AuthPatternsIndexRoute
  '/plugins/': typeof AuthPluginsIndexRoute
  '/posts/': typeof AuthPostsIndexRoute
  '/privacy/': typeof AuthPrivacyIndexRoute
  '/profile/': typeof AuthProfileIndexRoute
  '/roles/': typeof AuthRolesIndexRoute
  '/settings/': typeof AuthSettingsIndexRoute
  '/taxonomy/': typeof AuthTaxonomyIndexRoute
  '/users/': typeof AuthUsersIndexRoute
  '/webhooks/': typeof AuthWebhooksIndexRoute
  '/appearance/studio/$draftId': typeof AuthAppearanceStudioDraftIdRoute
}
export interface FileRoutesByTo {
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/setup': typeof SetupRoute
  '/verify': typeof VerifyRoute
  '/': typeof AuthIndexRoute
  '/content-types/$slug': typeof AuthContentTypesSlugRoute
  '/entries/$type': typeof AuthEntriesTypeRoute
  '/posts/$postId': typeof AuthPostsPostIdRoute
  '/appearance': typeof AuthAppearanceIndexRoute
  '/audience': typeof AuthAudienceIndexRoute
  '/comments': typeof AuthCommentsIndexRoute
  '/content-types': typeof AuthContentTypesIndexRoute
  '/forms': typeof AuthFormsIndexRoute
  '/health': typeof AuthHealthIndexRoute
  '/media': typeof AuthMediaIndexRoute
  '/menus': typeof AuthMenusIndexRoute
  '/models': typeof AuthModelsIndexRoute
  '/pages': typeof AuthPagesIndexRoute
  '/patterns': typeof AuthPatternsIndexRoute
  '/plugins': typeof AuthPluginsIndexRoute
  '/posts': typeof AuthPostsIndexRoute
  '/privacy': typeof AuthPrivacyIndexRoute
  '/profile': typeof AuthProfileIndexRoute
  '/roles': typeof AuthRolesIndexRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/taxonomy': typeof AuthTaxonomyIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/webhooks': typeof AuthWebhooksIndexRoute
  '/appearance/studio/$draftId': typeof AuthAppearanceStudioDraftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/forgot': typeof ForgotRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/setup': typeof SetupRoute
  '/verify': typeof VerifyRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/content-types/$slug': typeof AuthContentTypesSlugRoute
  '/_auth/entries/$type': typeof AuthEntriesTypeRoute
  '/_auth/posts/$postId': typeof AuthPostsPostIdRoute
  '/_auth/appearance/': typeof AuthAppearanceIndexRoute
  '/_auth/audience/': typeof AuthAudienceIndexRoute
  '/_auth/comments/': typeof AuthCommentsIndexRoute
  '/_auth/content-types/': typeof AuthContentTypesIndexRoute
  '/_auth/forms/': typeof AuthFormsIndexRoute
  '/_auth/health/': typeof AuthHealthIndexRoute
  '/_auth/media/': typeof AuthMediaIndexRoute
  '/_auth/menus/': typeof AuthMenusIndexRoute
  '/_auth/models/': typeof AuthModelsIndexRoute
  '/_auth/pages/': typeof AuthPagesIndexRoute
  '/_auth/patterns/': typeof AuthPatternsIndexRoute
  '/_auth/plugins/': typeof AuthPluginsIndexRoute
  '/_auth/posts/': typeof AuthPostsIndexRoute
  '/_auth/privacy/': typeof AuthPrivacyIndexRoute
  '/_auth/profile/': typeof AuthProfileIndexRoute
  '/_auth/roles/': typeof AuthRolesIndexRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/_auth/taxonomy/': typeof AuthTaxonomyIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
  '/_auth/webhooks/': typeof AuthWebhooksIndexRoute
  '/_auth/appearance/studio/$draftId': typeof AuthAppearanceStudioDraftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot'
    | '/login'
    | '/register'
    | '/reset'
    | '/setup'
    | '/verify'
    | '/content-types/$slug'
    | '/entries/$type'
    | '/posts/$postId'
    | '/appearance/'
    | '/audience/'
    | '/comments/'
    | '/content-types/'
    | '/forms/'
    | '/health/'
    | '/media/'
    | '/menus/'
    | '/models/'
    | '/pages/'
    | '/patterns/'
    | '/plugins/'
    | '/posts/'
    | '/privacy/'
    | '/profile/'
    | '/roles/'
    | '/settings/'
    | '/taxonomy/'
    | '/users/'
    | '/webhooks/'
    | '/appearance/studio/$draftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot'
    | '/login'
    | '/register'
    | '/reset'
    | '/setup'
    | '/verify'
    | '/'
    | '/content-types/$slug'
    | '/entries/$type'
    | '/posts/$postId'
    | '/appearance'
    | '/audience'
    | '/comments'
    | '/content-types'
    | '/forms'
    | '/health'
    | '/media'
    | '/menus'
    | '/models'
    | '/pages'
    | '/patterns'
    | '/plugins'
    | '/posts'
    | '/privacy'
    | '/profile'
    | '/roles'
    | '/settings'
    | '/taxonomy'
    | '/users'
    | '/webhooks'
    | '/appearance/studio/$draftId'
  id:
    | '__root__'
    | '/_auth'
    | '/forgot'
    | '/login'
    | '/register'
    | '/reset'
    | '/setup'
    | '/verify'
    | '/_auth/'
    | '/_auth/content-types/$slug'
    | '/_auth/entries/$type'
    | '/_auth/posts/$postId'
    | '/_auth/appearance/'
    | '/_auth/audience/'
    | '/_auth/comments/'
    | '/_auth/content-types/'
    | '/_auth/forms/'
    | '/_auth/health/'
    | '/_auth/media/'
    | '/_auth/menus/'
    | '/_auth/models/'
    | '/_auth/pages/'
    | '/_auth/patterns/'
    | '/_auth/plugins/'
    | '/_auth/posts/'
    | '/_auth/privacy/'
    | '/_auth/profile/'
    | '/_auth/roles/'
    | '/_auth/settings/'
    | '/_auth/taxonomy/'
    | '/_auth/users/'
    | '/_auth/webhooks/'
    | '/_auth/appearance/studio/$draftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ForgotRoute: typeof ForgotRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetRoute: typeof ResetRoute
  SetupRoute: typeof SetupRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/appearance/': {
      id: '/_auth/appearance/'
      path: '/appearance'
      fullPath: '/appearance/'
      preLoaderRoute: typeof AuthAppearanceIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/audience/': {
      id: '/_auth/audience/'
      path: '/audience'
      fullPath: '/audience/'
      preLoaderRoute: typeof AuthAudienceIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/comments/': {
      id: '/_auth/comments/'
      path: '/comments'
      fullPath: '/comments/'
      preLoaderRoute: typeof AuthCommentsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/content-types/': {
      id: '/_auth/content-types/'
      path: '/content-types'
      fullPath: '/content-types/'
      preLoaderRoute: typeof AuthContentTypesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/content-types/$slug': {
      id: '/_auth/content-types/$slug'
      path: '/content-types/$slug'
      fullPath: '/content-types/$slug'
      preLoaderRoute: typeof AuthContentTypesSlugRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/entries/$type': {
      id: '/_auth/entries/$type'
      path: '/entries/$type'
      fullPath: '/entries/$type'
      preLoaderRoute: typeof AuthEntriesTypeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forms/': {
      id: '/_auth/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof AuthFormsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/health/': {
      id: '/_auth/health/'
      path: '/health'
      fullPath: '/health/'
      preLoaderRoute: typeof AuthHealthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/media/': {
      id: '/_auth/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof AuthMediaIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/menus/': {
      id: '/_auth/menus/'
      path: '/menus'
      fullPath: '/menus/'
      preLoaderRoute: typeof AuthMenusIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/models/': {
      id: '/_auth/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof AuthModelsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pages/': {
      id: '/_auth/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof AuthPagesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/patterns/': {
      id: '/_auth/patterns/'
      path: '/patterns'
      fullPath: '/patterns/'
      preLoaderRoute: typeof AuthPatternsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/plugins/': {
      id: '/_auth/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof AuthPluginsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/posts/': {
      id: '/_auth/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthPostsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/posts/$postId': {
      id: '/_auth/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthPostsPostIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/privacy/': {
      id: '/_auth/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof AuthPrivacyIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile/': {
      id: '/_auth/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthProfileIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/roles/': {
      id: '/_auth/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthRolesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/taxonomy/': {
      id: '/_auth/taxonomy/'
      path: '/taxonomy'
      fullPath: '/taxonomy/'
      preLoaderRoute: typeof AuthTaxonomyIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/webhooks/': {
      id: '/_auth/webhooks/'
      path: '/webhooks'
      fullPath: '/webhooks/'
      preLoaderRoute: typeof AuthWebhooksIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/appearance/studio/$draftId': {
      id: '/_auth/appearance/studio/$draftId'
      path: '/appearance/studio/$draftId'
      fullPath: '/appearance/studio/$draftId'
      preLoaderRoute: typeof AuthAppearanceStudioDraftIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthContentTypesSlugRoute: typeof AuthContentTypesSlugRoute
  AuthEntriesTypeRoute: typeof AuthEntriesTypeRoute
  AuthPostsPostIdRoute: typeof AuthPostsPostIdRoute
  AuthAppearanceIndexRoute: typeof AuthAppearanceIndexRoute
  AuthAudienceIndexRoute: typeof AuthAudienceIndexRoute
  AuthCommentsIndexRoute: typeof AuthCommentsIndexRoute
  AuthContentTypesIndexRoute: typeof AuthContentTypesIndexRoute
  AuthFormsIndexRoute: typeof AuthFormsIndexRoute
  AuthHealthIndexRoute: typeof AuthHealthIndexRoute
  AuthMediaIndexRoute: typeof AuthMediaIndexRoute
  AuthMenusIndexRoute: typeof AuthMenusIndexRoute
  AuthModelsIndexRoute: typeof AuthModelsIndexRoute
  AuthPagesIndexRoute: typeof AuthPagesIndexRoute
  AuthPatternsIndexRoute: typeof AuthPatternsIndexRoute
  AuthPluginsIndexRoute: typeof AuthPluginsIndexRoute
  AuthPostsIndexRoute: typeof AuthPostsIndexRoute
  AuthPrivacyIndexRoute: typeof AuthPrivacyIndexRoute
  AuthProfileIndexRoute: typeof AuthProfileIndexRoute
  AuthRolesIndexRoute: typeof AuthRolesIndexRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
  AuthTaxonomyIndexRoute: typeof AuthTaxonomyIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
  AuthWebhooksIndexRoute: typeof AuthWebhooksIndexRoute
  AuthAppearanceStudioDraftIdRoute: typeof AuthAppearanceStudioDraftIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthContentTypesSlugRoute: AuthContentTypesSlugRoute,
  AuthEntriesTypeRoute: AuthEntriesTypeRoute,
  AuthPostsPostIdRoute: AuthPostsPostIdRoute,
  AuthAppearanceIndexRoute: AuthAppearanceIndexRoute,
  AuthAudienceIndexRoute: AuthAudienceIndexRoute,
  AuthCommentsIndexRoute: AuthCommentsIndexRoute,
  AuthContentTypesIndexRoute: AuthContentTypesIndexRoute,
  AuthFormsIndexRoute: AuthFormsIndexRoute,
  AuthHealthIndexRoute: AuthHealthIndexRoute,
  AuthMediaIndexRoute: AuthMediaIndexRoute,
  AuthMenusIndexRoute: AuthMenusIndexRoute,
  AuthModelsIndexRoute: AuthModelsIndexRoute,
  AuthPagesIndexRoute: AuthPagesIndexRoute,
  AuthPatternsIndexRoute: AuthPatternsIndexRoute,
  AuthPluginsIndexRoute: AuthPluginsIndexRoute,
  AuthPostsIndexRoute: AuthPostsIndexRoute,
  AuthPrivacyIndexRoute: AuthPrivacyIndexRoute,
  AuthProfileIndexRoute: AuthProfileIndexRoute,
  AuthRolesIndexRoute: AuthRolesIndexRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
  AuthTaxonomyIndexRoute: AuthTaxonomyIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
  AuthWebhooksIndexRoute: AuthWebhooksIndexRoute,
  AuthAppearanceStudioDraftIdRoute: AuthAppearanceStudioDraftIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ForgotRoute: ForgotRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetRoute: ResetRoute,
  SetupRoute: SetupRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
